//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_Project.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int P_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_SURNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_PHONE_NUMBERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_EMAIL_ADDRESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_STREET_ADDRESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_USERNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_PASSWORDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wedding_Project.ServiceReference1.Adminstrator[] AdminstratorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wedding_Project.ServiceReference1.Client[] ClientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wedding_Project.ServiceReference1.Wedding_Planner[] Wedding_PlannersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int P_ID {
            get {
                return this.P_IDField;
            }
            set {
                if ((this.P_IDField.Equals(value) != true)) {
                    this.P_IDField = value;
                    this.RaisePropertyChanged("P_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_NAME {
            get {
                return this.P_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.P_NAMEField, value) != true)) {
                    this.P_NAMEField = value;
                    this.RaisePropertyChanged("P_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_SURNAME {
            get {
                return this.P_SURNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.P_SURNAMEField, value) != true)) {
                    this.P_SURNAMEField = value;
                    this.RaisePropertyChanged("P_SURNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string P_PHONE_NUMBER {
            get {
                return this.P_PHONE_NUMBERField;
            }
            set {
                if ((object.ReferenceEquals(this.P_PHONE_NUMBERField, value) != true)) {
                    this.P_PHONE_NUMBERField = value;
                    this.RaisePropertyChanged("P_PHONE_NUMBER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string P_EMAIL_ADDRESS {
            get {
                return this.P_EMAIL_ADDRESSField;
            }
            set {
                if ((object.ReferenceEquals(this.P_EMAIL_ADDRESSField, value) != true)) {
                    this.P_EMAIL_ADDRESSField = value;
                    this.RaisePropertyChanged("P_EMAIL_ADDRESS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string P_STREET_ADDRESS {
            get {
                return this.P_STREET_ADDRESSField;
            }
            set {
                if ((object.ReferenceEquals(this.P_STREET_ADDRESSField, value) != true)) {
                    this.P_STREET_ADDRESSField = value;
                    this.RaisePropertyChanged("P_STREET_ADDRESS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string P_USERNAME {
            get {
                return this.P_USERNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.P_USERNAMEField, value) != true)) {
                    this.P_USERNAMEField = value;
                    this.RaisePropertyChanged("P_USERNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string P_PASSWORD {
            get {
                return this.P_PASSWORDField;
            }
            set {
                if ((object.ReferenceEquals(this.P_PASSWORDField, value) != true)) {
                    this.P_PASSWORDField = value;
                    this.RaisePropertyChanged("P_PASSWORD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public Wedding_Project.ServiceReference1.Adminstrator[] Adminstrators {
            get {
                return this.AdminstratorsField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminstratorsField, value) != true)) {
                    this.AdminstratorsField = value;
                    this.RaisePropertyChanged("Adminstrators");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public Wedding_Project.ServiceReference1.Client[] Clients {
            get {
                return this.ClientsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientsField, value) != true)) {
                    this.ClientsField = value;
                    this.RaisePropertyChanged("Clients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public Wedding_Project.ServiceReference1.Wedding_Planner[] Wedding_Planners {
            get {
                return this.Wedding_PlannersField;
            }
            set {
                if ((object.ReferenceEquals(this.Wedding_PlannersField, value) != true)) {
                    this.Wedding_PlannersField = value;
                    this.RaisePropertyChanged("Wedding_Planners");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Adminstrator", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Adminstrator : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ADM_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> P_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LOGIN_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ADM_ID {
            get {
                return this.ADM_IDField;
            }
            set {
                if ((this.ADM_IDField.Equals(value) != true)) {
                    this.ADM_IDField = value;
                    this.RaisePropertyChanged("ADM_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> P_ID {
            get {
                return this.P_IDField;
            }
            set {
                if ((this.P_IDField.Equals(value) != true)) {
                    this.P_IDField = value;
                    this.RaisePropertyChanged("P_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> LOGIN_ID {
            get {
                return this.LOGIN_IDField;
            }
            set {
                if ((this.LOGIN_IDField.Equals(value) != true)) {
                    this.LOGIN_IDField = value;
                    this.RaisePropertyChanged("LOGIN_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CL_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> P_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LOGIN_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CL_ID {
            get {
                return this.CL_IDField;
            }
            set {
                if ((this.CL_IDField.Equals(value) != true)) {
                    this.CL_IDField = value;
                    this.RaisePropertyChanged("CL_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> P_ID {
            get {
                return this.P_IDField;
            }
            set {
                if ((this.P_IDField.Equals(value) != true)) {
                    this.P_IDField = value;
                    this.RaisePropertyChanged("P_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> LOGIN_ID {
            get {
                return this.LOGIN_IDField;
            }
            set {
                if ((this.LOGIN_IDField.Equals(value) != true)) {
                    this.LOGIN_IDField = value;
                    this.RaisePropertyChanged("LOGIN_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Wedding_Planner", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Wedding_Planner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WP_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WP_HISTORYDESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> P_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LOGIN_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wedding_Project.ServiceReference1.Wedding_Planner_Working_Location[] Wedding_Planner_Working_LocationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WP_ID {
            get {
                return this.WP_IDField;
            }
            set {
                if ((this.WP_IDField.Equals(value) != true)) {
                    this.WP_IDField = value;
                    this.RaisePropertyChanged("WP_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string WP_HISTORYDESCRIPTION {
            get {
                return this.WP_HISTORYDESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.WP_HISTORYDESCRIPTIONField, value) != true)) {
                    this.WP_HISTORYDESCRIPTIONField = value;
                    this.RaisePropertyChanged("WP_HISTORYDESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> P_ID {
            get {
                return this.P_IDField;
            }
            set {
                if ((this.P_IDField.Equals(value) != true)) {
                    this.P_IDField = value;
                    this.RaisePropertyChanged("P_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> LOGIN_ID {
            get {
                return this.LOGIN_IDField;
            }
            set {
                if ((this.LOGIN_IDField.Equals(value) != true)) {
                    this.LOGIN_IDField = value;
                    this.RaisePropertyChanged("LOGIN_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Wedding_Project.ServiceReference1.Wedding_Planner_Working_Location[] Wedding_Planner_Working_Locations {
            get {
                return this.Wedding_Planner_Working_LocationsField;
            }
            set {
                if ((object.ReferenceEquals(this.Wedding_Planner_Working_LocationsField, value) != true)) {
                    this.Wedding_Planner_Working_LocationsField = value;
                    this.RaisePropertyChanged("Wedding_Planner_Working_Locations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Wedding_Planner_Working_Location", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Wedding_Planner_Working_Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WPWL_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WPWL_PROVINCEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WP_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WPWL_ID {
            get {
                return this.WPWL_IDField;
            }
            set {
                if ((this.WPWL_IDField.Equals(value) != true)) {
                    this.WPWL_IDField = value;
                    this.RaisePropertyChanged("WPWL_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WPWL_PROVINCE {
            get {
                return this.WPWL_PROVINCEField;
            }
            set {
                if ((object.ReferenceEquals(this.WPWL_PROVINCEField, value) != true)) {
                    this.WPWL_PROVINCEField = value;
                    this.RaisePropertyChanged("WPWL_PROVINCE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WP_ID {
            get {
                return this.WP_IDField;
            }
            set {
                if ((this.WP_IDField.Equals(value) != true)) {
                    this.WP_IDField = value;
                    this.RaisePropertyChanged("WP_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        Wedding_Project.ServiceReference1.CompositeType GetDataUsingDataContract(Wedding_Project.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Wedding_Project.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(Wedding_Project.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPerson", ReplyAction="http://tempuri.org/IService1/GetPersonResponse")]
        Wedding_Project.ServiceReference1.Person[] GetPerson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPerson", ReplyAction="http://tempuri.org/IService1/GetPersonResponse")]
        System.Threading.Tasks.Task<Wedding_Project.ServiceReference1.Person[]> GetPersonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllWeddingPlanners", ReplyAction="http://tempuri.org/IService1/GetAllWeddingPlannersResponse")]
        Wedding_Project.ServiceReference1.Wedding_Planner[] GetAllWeddingPlanners();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllWeddingPlanners", ReplyAction="http://tempuri.org/IService1/GetAllWeddingPlannersResponse")]
        System.Threading.Tasks.Task<Wedding_Project.ServiceReference1.Wedding_Planner[]> GetAllWeddingPlannersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Test", ReplyAction="http://tempuri.org/IService1/TestResponse")]
        string Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Test", ReplyAction="http://tempuri.org/IService1/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Wedding_Project.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Wedding_Project.ServiceReference1.IService1>, Wedding_Project.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Wedding_Project.ServiceReference1.CompositeType GetDataUsingDataContract(Wedding_Project.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Wedding_Project.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(Wedding_Project.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public Wedding_Project.ServiceReference1.Person[] GetPerson() {
            return base.Channel.GetPerson();
        }
        
        public System.Threading.Tasks.Task<Wedding_Project.ServiceReference1.Person[]> GetPersonAsync() {
            return base.Channel.GetPersonAsync();
        }
        
        public Wedding_Project.ServiceReference1.Wedding_Planner[] GetAllWeddingPlanners() {
            return base.Channel.GetAllWeddingPlanners();
        }
        
        public System.Threading.Tasks.Task<Wedding_Project.ServiceReference1.Wedding_Planner[]> GetAllWeddingPlannersAsync() {
            return base.Channel.GetAllWeddingPlannersAsync();
        }
        
        public string Test() {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<string> TestAsync() {
            return base.Channel.TestAsync();
        }
    }
}
