//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_Project.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int P_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_SURNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_PHONE_NUMBERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_EMAIL_ADDRESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_STREET_ADDRESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_USERNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_PASSWORDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wedding_Project.ServiceReference1.Adminstrator[] AdminstratorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wedding_Project.ServiceReference1.Client[] ClientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wedding_Project.ServiceReference1.Wedding_Planner[] Wedding_PlannersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int P_ID {
            get {
                return this.P_IDField;
            }
            set {
                if ((this.P_IDField.Equals(value) != true)) {
                    this.P_IDField = value;
                    this.RaisePropertyChanged("P_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_NAME {
            get {
                return this.P_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.P_NAMEField, value) != true)) {
                    this.P_NAMEField = value;
                    this.RaisePropertyChanged("P_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_SURNAME {
            get {
                return this.P_SURNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.P_SURNAMEField, value) != true)) {
                    this.P_SURNAMEField = value;
                    this.RaisePropertyChanged("P_SURNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string P_PHONE_NUMBER {
            get {
                return this.P_PHONE_NUMBERField;
            }
            set {
                if ((object.ReferenceEquals(this.P_PHONE_NUMBERField, value) != true)) {
                    this.P_PHONE_NUMBERField = value;
                    this.RaisePropertyChanged("P_PHONE_NUMBER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string P_EMAIL_ADDRESS {
            get {
                return this.P_EMAIL_ADDRESSField;
            }
            set {
                if ((object.ReferenceEquals(this.P_EMAIL_ADDRESSField, value) != true)) {
                    this.P_EMAIL_ADDRESSField = value;
                    this.RaisePropertyChanged("P_EMAIL_ADDRESS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string P_STREET_ADDRESS {
            get {
                return this.P_STREET_ADDRESSField;
            }
            set {
                if ((object.ReferenceEquals(this.P_STREET_ADDRESSField, value) != true)) {
                    this.P_STREET_ADDRESSField = value;
                    this.RaisePropertyChanged("P_STREET_ADDRESS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string P_USERNAME {
            get {
                return this.P_USERNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.P_USERNAMEField, value) != true)) {
                    this.P_USERNAMEField = value;
                    this.RaisePropertyChanged("P_USERNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string P_PASSWORD {
            get {
                return this.P_PASSWORDField;
            }
            set {
                if ((object.ReferenceEquals(this.P_PASSWORDField, value) != true)) {
                    this.P_PASSWORDField = value;
                    this.RaisePropertyChanged("P_PASSWORD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public Wedding_Project.ServiceReference1.Adminstrator[] Adminstrators {
            get {
                return this.AdminstratorsField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminstratorsField, value) != true)) {
                    this.AdminstratorsField = value;
                    this.RaisePropertyChanged("Adminstrators");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public Wedding_Project.ServiceReference1.Client[] Clients {
            get {
                return this.ClientsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientsField, value) != true)) {
                    this.ClientsField = value;
                    this.RaisePropertyChanged("Clients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public Wedding_Project.ServiceReference1.Wedding_Planner[] Wedding_Planners {
            get {
                return this.Wedding_PlannersField;
            }
            set {
                if ((object.ReferenceEquals(this.Wedding_PlannersField, value) != true)) {
                    this.Wedding_PlannersField = value;
                    this.RaisePropertyChanged("Wedding_Planners");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Adminstrator", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Adminstrator : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ADM_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> P_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LOGIN_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ADM_ID {
            get {
                return this.ADM_IDField;
            }
            set {
                if ((this.ADM_IDField.Equals(value) != true)) {
                    this.ADM_IDField = value;
                    this.RaisePropertyChanged("ADM_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> P_ID {
            get {
                return this.P_IDField;
            }
            set {
                if ((this.P_IDField.Equals(value) != true)) {
                    this.P_IDField = value;
                    this.RaisePropertyChanged("P_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> LOGIN_ID {
            get {
                return this.LOGIN_IDField;
            }
            set {
                if ((this.LOGIN_IDField.Equals(value) != true)) {
                    this.LOGIN_IDField = value;
                    this.RaisePropertyChanged("LOGIN_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CL_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> P_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LOGIN_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CL_ID {
            get {
                return this.CL_IDField;
            }
            set {
                if ((this.CL_IDField.Equals(value) != true)) {
                    this.CL_IDField = value;
                    this.RaisePropertyChanged("CL_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> P_ID {
            get {
                return this.P_IDField;
            }
            set {
                if ((this.P_IDField.Equals(value) != true)) {
                    this.P_IDField = value;
                    this.RaisePropertyChanged("P_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> LOGIN_ID {
            get {
                return this.LOGIN_IDField;
            }
            set {
                if ((this.LOGIN_IDField.Equals(value) != true)) {
                    this.LOGIN_IDField = value;
                    this.RaisePropertyChanged("LOGIN_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Wedding_Planner", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Wedding_Planner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WP_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WP_HISTORYDESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int P_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LOGIN_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WP_IMAGELOCATIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wedding_Project.ServiceReference1.WP_Working_Location[] WP_Working_LocationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WP_ID {
            get {
                return this.WP_IDField;
            }
            set {
                if ((this.WP_IDField.Equals(value) != true)) {
                    this.WP_IDField = value;
                    this.RaisePropertyChanged("WP_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string WP_HISTORYDESCRIPTION {
            get {
                return this.WP_HISTORYDESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.WP_HISTORYDESCRIPTIONField, value) != true)) {
                    this.WP_HISTORYDESCRIPTIONField = value;
                    this.RaisePropertyChanged("WP_HISTORYDESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int P_ID {
            get {
                return this.P_IDField;
            }
            set {
                if ((this.P_IDField.Equals(value) != true)) {
                    this.P_IDField = value;
                    this.RaisePropertyChanged("P_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int LOGIN_ID {
            get {
                return this.LOGIN_IDField;
            }
            set {
                if ((this.LOGIN_IDField.Equals(value) != true)) {
                    this.LOGIN_IDField = value;
                    this.RaisePropertyChanged("LOGIN_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string WP_IMAGELOCATION {
            get {
                return this.WP_IMAGELOCATIONField;
            }
            set {
                if ((object.ReferenceEquals(this.WP_IMAGELOCATIONField, value) != true)) {
                    this.WP_IMAGELOCATIONField = value;
                    this.RaisePropertyChanged("WP_IMAGELOCATION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Wedding_Project.ServiceReference1.WP_Working_Location[] WP_Working_Locations {
            get {
                return this.WP_Working_LocationsField;
            }
            set {
                if ((object.ReferenceEquals(this.WP_Working_LocationsField, value) != true)) {
                    this.WP_Working_LocationsField = value;
                    this.RaisePropertyChanged("WP_Working_Locations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WP_Working_Location", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class WP_Working_Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WPWL_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WPWL_PROVINCEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WP_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WPWL_ID {
            get {
                return this.WPWL_IDField;
            }
            set {
                if ((this.WPWL_IDField.Equals(value) != true)) {
                    this.WPWL_IDField = value;
                    this.RaisePropertyChanged("WPWL_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WPWL_PROVINCE {
            get {
                return this.WPWL_PROVINCEField;
            }
            set {
                if ((object.ReferenceEquals(this.WPWL_PROVINCEField, value) != true)) {
                    this.WPWL_PROVINCEField = value;
                    this.RaisePropertyChanged("WPWL_PROVINCE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WP_ID {
            get {
                return this.WP_IDField;
            }
            set {
                if ((this.WP_IDField.Equals(value) != true)) {
                    this.WP_IDField = value;
                    this.RaisePropertyChanged("WP_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venue", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Venue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VN_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VN_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VN_STREET_ADDRESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VN_CAPACITYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> VN_PRICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VN_COORDINATESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VN_IMAGE_PATHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wedding_Project.ServiceReference1.Venue_Booking_Schedule[] Venue_Booking_SchedulesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wedding_Project.ServiceReference1.Venue_Contractor[] Venue_ContractorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wedding_Project.ServiceReference1.Venue_Decor_Invoice[] Venue_Decor_InvoicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wedding_Project.ServiceReference1.Venue_Decor_Invoice[] Venue_Decor_Invoices1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wedding_Project.ServiceReference1.Venue_Location_and_Contact_Detail[] Venue_Location_and_Contact_DetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VN_ID {
            get {
                return this.VN_IDField;
            }
            set {
                if ((this.VN_IDField.Equals(value) != true)) {
                    this.VN_IDField = value;
                    this.RaisePropertyChanged("VN_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VN_NAME {
            get {
                return this.VN_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.VN_NAMEField, value) != true)) {
                    this.VN_NAMEField = value;
                    this.RaisePropertyChanged("VN_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VN_STREET_ADDRESS {
            get {
                return this.VN_STREET_ADDRESSField;
            }
            set {
                if ((object.ReferenceEquals(this.VN_STREET_ADDRESSField, value) != true)) {
                    this.VN_STREET_ADDRESSField = value;
                    this.RaisePropertyChanged("VN_STREET_ADDRESS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> VN_CAPACITY {
            get {
                return this.VN_CAPACITYField;
            }
            set {
                if ((this.VN_CAPACITYField.Equals(value) != true)) {
                    this.VN_CAPACITYField = value;
                    this.RaisePropertyChanged("VN_CAPACITY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<decimal> VN_PRICE {
            get {
                return this.VN_PRICEField;
            }
            set {
                if ((this.VN_PRICEField.Equals(value) != true)) {
                    this.VN_PRICEField = value;
                    this.RaisePropertyChanged("VN_PRICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string VN_COORDINATES {
            get {
                return this.VN_COORDINATESField;
            }
            set {
                if ((object.ReferenceEquals(this.VN_COORDINATESField, value) != true)) {
                    this.VN_COORDINATESField = value;
                    this.RaisePropertyChanged("VN_COORDINATES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string VN_IMAGE_PATH {
            get {
                return this.VN_IMAGE_PATHField;
            }
            set {
                if ((object.ReferenceEquals(this.VN_IMAGE_PATHField, value) != true)) {
                    this.VN_IMAGE_PATHField = value;
                    this.RaisePropertyChanged("VN_IMAGE_PATH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public Wedding_Project.ServiceReference1.Venue_Booking_Schedule[] Venue_Booking_Schedules {
            get {
                return this.Venue_Booking_SchedulesField;
            }
            set {
                if ((object.ReferenceEquals(this.Venue_Booking_SchedulesField, value) != true)) {
                    this.Venue_Booking_SchedulesField = value;
                    this.RaisePropertyChanged("Venue_Booking_Schedules");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public Wedding_Project.ServiceReference1.Venue_Contractor[] Venue_Contractors {
            get {
                return this.Venue_ContractorsField;
            }
            set {
                if ((object.ReferenceEquals(this.Venue_ContractorsField, value) != true)) {
                    this.Venue_ContractorsField = value;
                    this.RaisePropertyChanged("Venue_Contractors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public Wedding_Project.ServiceReference1.Venue_Decor_Invoice[] Venue_Decor_Invoices {
            get {
                return this.Venue_Decor_InvoicesField;
            }
            set {
                if ((object.ReferenceEquals(this.Venue_Decor_InvoicesField, value) != true)) {
                    this.Venue_Decor_InvoicesField = value;
                    this.RaisePropertyChanged("Venue_Decor_Invoices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public Wedding_Project.ServiceReference1.Venue_Decor_Invoice[] Venue_Decor_Invoices1 {
            get {
                return this.Venue_Decor_Invoices1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Venue_Decor_Invoices1Field, value) != true)) {
                    this.Venue_Decor_Invoices1Field = value;
                    this.RaisePropertyChanged("Venue_Decor_Invoices1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public Wedding_Project.ServiceReference1.Venue_Location_and_Contact_Detail[] Venue_Location_and_Contact_Details {
            get {
                return this.Venue_Location_and_Contact_DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.Venue_Location_and_Contact_DetailsField, value) != true)) {
                    this.Venue_Location_and_Contact_DetailsField = value;
                    this.RaisePropertyChanged("Venue_Location_and_Contact_Details");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venue_Booking_Schedule", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Venue_Booking_Schedule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VBS_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> VBS_START_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> VBS_END_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VN_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VBS_ID {
            get {
                return this.VBS_IDField;
            }
            set {
                if ((this.VBS_IDField.Equals(value) != true)) {
                    this.VBS_IDField = value;
                    this.RaisePropertyChanged("VBS_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> VBS_START_DATE {
            get {
                return this.VBS_START_DATEField;
            }
            set {
                if ((this.VBS_START_DATEField.Equals(value) != true)) {
                    this.VBS_START_DATEField = value;
                    this.RaisePropertyChanged("VBS_START_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> VBS_END_DATE {
            get {
                return this.VBS_END_DATEField;
            }
            set {
                if ((this.VBS_END_DATEField.Equals(value) != true)) {
                    this.VBS_END_DATEField = value;
                    this.RaisePropertyChanged("VBS_END_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> VN_ID {
            get {
                return this.VN_IDField;
            }
            set {
                if ((this.VN_IDField.Equals(value) != true)) {
                    this.VN_IDField = value;
                    this.RaisePropertyChanged("VN_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venue_Contractor", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Venue_Contractor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VNC_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VNC_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VNC_SURNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VNC_EMAIL_ADDRESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VNC_PHONE_NUMBERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> VNC_RATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VN_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wedding_Project.ServiceReference1.Disc_Jockey[] Disc_JockeysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wedding_Project.ServiceReference1.Master_of_Ceremony[] Master_of_CeremoniesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wedding_Project.ServiceReference1.Photographer[] PhotographersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wedding_Project.ServiceReference1.Videoagrapher[] VideoagraphersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VNC_ID {
            get {
                return this.VNC_IDField;
            }
            set {
                if ((this.VNC_IDField.Equals(value) != true)) {
                    this.VNC_IDField = value;
                    this.RaisePropertyChanged("VNC_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VNC_NAME {
            get {
                return this.VNC_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.VNC_NAMEField, value) != true)) {
                    this.VNC_NAMEField = value;
                    this.RaisePropertyChanged("VNC_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VNC_SURNAME {
            get {
                return this.VNC_SURNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.VNC_SURNAMEField, value) != true)) {
                    this.VNC_SURNAMEField = value;
                    this.RaisePropertyChanged("VNC_SURNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string VNC_EMAIL_ADDRESS {
            get {
                return this.VNC_EMAIL_ADDRESSField;
            }
            set {
                if ((object.ReferenceEquals(this.VNC_EMAIL_ADDRESSField, value) != true)) {
                    this.VNC_EMAIL_ADDRESSField = value;
                    this.RaisePropertyChanged("VNC_EMAIL_ADDRESS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> VNC_PHONE_NUMBER {
            get {
                return this.VNC_PHONE_NUMBERField;
            }
            set {
                if ((this.VNC_PHONE_NUMBERField.Equals(value) != true)) {
                    this.VNC_PHONE_NUMBERField = value;
                    this.RaisePropertyChanged("VNC_PHONE_NUMBER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<decimal> VNC_RATE {
            get {
                return this.VNC_RATEField;
            }
            set {
                if ((this.VNC_RATEField.Equals(value) != true)) {
                    this.VNC_RATEField = value;
                    this.RaisePropertyChanged("VNC_RATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<int> VN_ID {
            get {
                return this.VN_IDField;
            }
            set {
                if ((this.VN_IDField.Equals(value) != true)) {
                    this.VN_IDField = value;
                    this.RaisePropertyChanged("VN_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public Wedding_Project.ServiceReference1.Disc_Jockey[] Disc_Jockeys {
            get {
                return this.Disc_JockeysField;
            }
            set {
                if ((object.ReferenceEquals(this.Disc_JockeysField, value) != true)) {
                    this.Disc_JockeysField = value;
                    this.RaisePropertyChanged("Disc_Jockeys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public Wedding_Project.ServiceReference1.Master_of_Ceremony[] Master_of_Ceremonies {
            get {
                return this.Master_of_CeremoniesField;
            }
            set {
                if ((object.ReferenceEquals(this.Master_of_CeremoniesField, value) != true)) {
                    this.Master_of_CeremoniesField = value;
                    this.RaisePropertyChanged("Master_of_Ceremonies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public Wedding_Project.ServiceReference1.Photographer[] Photographers {
            get {
                return this.PhotographersField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotographersField, value) != true)) {
                    this.PhotographersField = value;
                    this.RaisePropertyChanged("Photographers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public Wedding_Project.ServiceReference1.Videoagrapher[] Videoagraphers {
            get {
                return this.VideoagraphersField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoagraphersField, value) != true)) {
                    this.VideoagraphersField = value;
                    this.RaisePropertyChanged("Videoagraphers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venue_Decor_Invoice", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Venue_Decor_Invoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DEC_VN_INV_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DEC_VN_INV_DECORINVOICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DEC_VN_INV_VENUEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VN_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DEC_VN_INV_ID {
            get {
                return this.DEC_VN_INV_IDField;
            }
            set {
                if ((this.DEC_VN_INV_IDField.Equals(value) != true)) {
                    this.DEC_VN_INV_IDField = value;
                    this.RaisePropertyChanged("DEC_VN_INV_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<int> DEC_VN_INV_DECORINVOICE {
            get {
                return this.DEC_VN_INV_DECORINVOICEField;
            }
            set {
                if ((this.DEC_VN_INV_DECORINVOICEField.Equals(value) != true)) {
                    this.DEC_VN_INV_DECORINVOICEField = value;
                    this.RaisePropertyChanged("DEC_VN_INV_DECORINVOICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> DEC_VN_INV_VENUE {
            get {
                return this.DEC_VN_INV_VENUEField;
            }
            set {
                if ((this.DEC_VN_INV_VENUEField.Equals(value) != true)) {
                    this.DEC_VN_INV_VENUEField = value;
                    this.RaisePropertyChanged("DEC_VN_INV_VENUE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> VN_ID {
            get {
                return this.VN_IDField;
            }
            set {
                if ((this.VN_IDField.Equals(value) != true)) {
                    this.VN_IDField = value;
                    this.RaisePropertyChanged("VN_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venue_Location_and_Contact_Detail", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Venue_Location_and_Contact_Detail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LOC_LOCATION_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOC_STREET_ADDRESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOC_PROVINCEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOC_GPS_COORDINATESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOC_PHONE_NUMBERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOC_EMAIL_ADDRESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VN_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LOC_LOCATION_ID {
            get {
                return this.LOC_LOCATION_IDField;
            }
            set {
                if ((this.LOC_LOCATION_IDField.Equals(value) != true)) {
                    this.LOC_LOCATION_IDField = value;
                    this.RaisePropertyChanged("LOC_LOCATION_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOC_STREET_ADDRESS {
            get {
                return this.LOC_STREET_ADDRESSField;
            }
            set {
                if ((object.ReferenceEquals(this.LOC_STREET_ADDRESSField, value) != true)) {
                    this.LOC_STREET_ADDRESSField = value;
                    this.RaisePropertyChanged("LOC_STREET_ADDRESS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string LOC_PROVINCE {
            get {
                return this.LOC_PROVINCEField;
            }
            set {
                if ((object.ReferenceEquals(this.LOC_PROVINCEField, value) != true)) {
                    this.LOC_PROVINCEField = value;
                    this.RaisePropertyChanged("LOC_PROVINCE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string LOC_GPS_COORDINATES {
            get {
                return this.LOC_GPS_COORDINATESField;
            }
            set {
                if ((object.ReferenceEquals(this.LOC_GPS_COORDINATESField, value) != true)) {
                    this.LOC_GPS_COORDINATESField = value;
                    this.RaisePropertyChanged("LOC_GPS_COORDINATES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string LOC_PHONE_NUMBER {
            get {
                return this.LOC_PHONE_NUMBERField;
            }
            set {
                if ((object.ReferenceEquals(this.LOC_PHONE_NUMBERField, value) != true)) {
                    this.LOC_PHONE_NUMBERField = value;
                    this.RaisePropertyChanged("LOC_PHONE_NUMBER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string LOC_EMAIL_ADDRESS {
            get {
                return this.LOC_EMAIL_ADDRESSField;
            }
            set {
                if ((object.ReferenceEquals(this.LOC_EMAIL_ADDRESSField, value) != true)) {
                    this.LOC_EMAIL_ADDRESSField = value;
                    this.RaisePropertyChanged("LOC_EMAIL_ADDRESS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<int> VN_ID {
            get {
                return this.VN_IDField;
            }
            set {
                if ((this.VN_IDField.Equals(value) != true)) {
                    this.VN_IDField = value;
                    this.RaisePropertyChanged("VN_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Disc_Jockey", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Disc_Jockey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DJ_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DJ_STAGENAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VNC_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DJ_ID {
            get {
                return this.DJ_IDField;
            }
            set {
                if ((this.DJ_IDField.Equals(value) != true)) {
                    this.DJ_IDField = value;
                    this.RaisePropertyChanged("DJ_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DJ_STAGENAME {
            get {
                return this.DJ_STAGENAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.DJ_STAGENAMEField, value) != true)) {
                    this.DJ_STAGENAMEField = value;
                    this.RaisePropertyChanged("DJ_STAGENAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VNC_ID {
            get {
                return this.VNC_IDField;
            }
            set {
                if ((this.VNC_IDField.Equals(value) != true)) {
                    this.VNC_IDField = value;
                    this.RaisePropertyChanged("VNC_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Master_of_Ceremony", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Master_of_Ceremony : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MC_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MC_STAGENAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VNC_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MC_ID {
            get {
                return this.MC_IDField;
            }
            set {
                if ((this.MC_IDField.Equals(value) != true)) {
                    this.MC_IDField = value;
                    this.RaisePropertyChanged("MC_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MC_STAGENAME {
            get {
                return this.MC_STAGENAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.MC_STAGENAMEField, value) != true)) {
                    this.MC_STAGENAMEField = value;
                    this.RaisePropertyChanged("MC_STAGENAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VNC_ID {
            get {
                return this.VNC_IDField;
            }
            set {
                if ((this.VNC_IDField.Equals(value) != true)) {
                    this.VNC_IDField = value;
                    this.RaisePropertyChanged("VNC_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Photographer", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Photographer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PHO_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VNC_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PHO_ID {
            get {
                return this.PHO_IDField;
            }
            set {
                if ((this.PHO_IDField.Equals(value) != true)) {
                    this.PHO_IDField = value;
                    this.RaisePropertyChanged("PHO_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VNC_ID {
            get {
                return this.VNC_IDField;
            }
            set {
                if ((this.VNC_IDField.Equals(value) != true)) {
                    this.VNC_IDField = value;
                    this.RaisePropertyChanged("VNC_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Videoagrapher", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Videoagrapher : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VID_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VNC_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VID_ID {
            get {
                return this.VID_IDField;
            }
            set {
                if ((this.VID_IDField.Equals(value) != true)) {
                    this.VID_IDField = value;
                    this.RaisePropertyChanged("VID_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VNC_ID {
            get {
                return this.VNC_IDField;
            }
            set {
                if ((this.VNC_IDField.Equals(value) != true)) {
                    this.VNC_IDField = value;
                    this.RaisePropertyChanged("VNC_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        Wedding_Project.ServiceReference1.CompositeType GetDataUsingDataContract(Wedding_Project.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Wedding_Project.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(Wedding_Project.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPerson", ReplyAction="http://tempuri.org/IService1/GetPersonResponse")]
        Wedding_Project.ServiceReference1.Person[] GetPerson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPerson", ReplyAction="http://tempuri.org/IService1/GetPersonResponse")]
        System.Threading.Tasks.Task<Wedding_Project.ServiceReference1.Person[]> GetPersonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllWeddingPlanners", ReplyAction="http://tempuri.org/IService1/GetAllWeddingPlannersResponse")]
        Wedding_Project.ServiceReference1.Wedding_Planner[] GetAllWeddingPlanners();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllWeddingPlanners", ReplyAction="http://tempuri.org/IService1/GetAllWeddingPlannersResponse")]
        System.Threading.Tasks.Task<Wedding_Project.ServiceReference1.Wedding_Planner[]> GetAllWeddingPlannersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Test", ReplyAction="http://tempuri.org/IService1/TestResponse")]
        string Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Test", ReplyAction="http://tempuri.org/IService1/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllVenues", ReplyAction="http://tempuri.org/IService1/GetAllVenuesResponse")]
        Wedding_Project.ServiceReference1.Venue[] GetAllVenues();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllVenues", ReplyAction="http://tempuri.org/IService1/GetAllVenuesResponse")]
        System.Threading.Tasks.Task<Wedding_Project.ServiceReference1.Venue[]> GetAllVenuesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Wedding_Project.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Wedding_Project.ServiceReference1.IService1>, Wedding_Project.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Wedding_Project.ServiceReference1.CompositeType GetDataUsingDataContract(Wedding_Project.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Wedding_Project.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(Wedding_Project.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public Wedding_Project.ServiceReference1.Person[] GetPerson() {
            return base.Channel.GetPerson();
        }
        
        public System.Threading.Tasks.Task<Wedding_Project.ServiceReference1.Person[]> GetPersonAsync() {
            return base.Channel.GetPersonAsync();
        }
        
        public Wedding_Project.ServiceReference1.Wedding_Planner[] GetAllWeddingPlanners() {
            return base.Channel.GetAllWeddingPlanners();
        }
        
        public System.Threading.Tasks.Task<Wedding_Project.ServiceReference1.Wedding_Planner[]> GetAllWeddingPlannersAsync() {
            return base.Channel.GetAllWeddingPlannersAsync();
        }
        
        public string Test() {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<string> TestAsync() {
            return base.Channel.TestAsync();
        }
        
        public Wedding_Project.ServiceReference1.Venue[] GetAllVenues() {
            return base.Channel.GetAllVenues();
        }
        
        public System.Threading.Tasks.Task<Wedding_Project.ServiceReference1.Venue[]> GetAllVenuesAsync() {
            return base.Channel.GetAllVenuesAsync();
        }
    }
}
